# Generated by Django 5.0.1 on 2024-03-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_etudiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatedResult',
        ),
    ]
